/* eslint-disable */
// Generated by scripts/gen-events.mjs. Do not edit by hand.
// Source: https://github.com/mindreon/orbit-runtime/blob/2c56c2ad9e7429454f590cd19a790987f5841db5/schema/OrbitEvent.json

/**
 * Normalized event the worker may ingest. Control rejects unknown types.
 *
 * The wire form is camelCase (``model_dump(by_alias=True)``).
 */
export interface OrbitEvent {
  activityAttempt?: number;
  agentId?: string;
  agentPath?: string;
  answer?: QuestionAnswer | null;
  approvalRequestId?: string;
  argsPreview?: string;
  blockId?: string;
  cacheCreationInputTokens?: number;
  cacheInputTokens?: number;
  callId?: string;
  decidedBy?: string;
  delta?: string;
  depth?: number;
  errorCode?:
    | (
        | "APPROVAL_REJECTED"
        | "PERMISSION_DENIED"
        | "DELEGATION_LIMIT_EXCEEDED"
        | "QUESTION_CANCELLED"
        | "SESSION_ABORTED"
      )
    | null;
  eventId?: string;
  failure?: TurnFailure | null;
  inputTokens?: number;
  jobId?: string;
  latencyMs?: number;
  limit?: string;
  limitCurrent?: number;
  limitMax?: number;
  model?: string;
  modelMode?: string;
  modelName?: string;
  occurredAt?: string;
  outcome?: string;
  outputTokens?: number;
  parentAgentId?: string | null;
  parentSessionId?: string | null;
  permissionPreset?: string;
  persona?: string;
  question?: QuestionAsk | null;
  risk?: ("read" | "write" | "sensitive" | "destructive") | null;
  roomId: string;
  runtime?: string;
  runtimeVersion?: string;
  seq?: number;
  sessionId: string;
  status?: string;
  text?: string;
  todoRevision?: number;
  todos?: TodoItem[] | null;
  toolName?: string;
  toolState?: ("success" | "error" | "denied" | "interrupted") | null;
  turnId?: string;
  type:
    | "session.status"
    | "assistant.message"
    | "assistant.delta"
    | "tool.call"
    | "tool.result"
    | "approval.asked"
    | "approval.resolved"
    | "question.asked"
    | "question.answered"
    | "todo.updated"
    | "usage"
    | "agent.started"
    | "agent.finished"
    | "agent.spawn_rejected"
    | "turn.failed";
}
export interface QuestionAnswer {
  choiceIds?: string[];
  questionId: string;
  text?: string;
}
/**
 * Payload of a ``turn.failed`` event: ``{turnId, agentId, errorCode, retryable, message}``.
 *
 * ``agent_id`` is the contract agent id (``main`` for the room agent), not
 * the session id. ``message`` is the fixed text for ``error_code``, never
 * built from provider or exception text.
 */
export interface TurnFailure {
  agentId: string;
  errorCode: "timeout" | "auth" | "rate_limited" | "provider_error" | "config";
  message: string;
  retryable: boolean;
  turnId: string;
}
export interface QuestionAsk {
  agent?: AgentRef;
  allowCustom?: boolean;
  choices?: QuestionChoice[];
  questionId: string;
  text: string;
}
/**
 * Identity of one agent in a room. The main agent is always ``main``.
 */
export interface AgentRef {
  agentId?: string;
  agentPath?: string;
  depth?: number;
  parentAgentId?: string | null;
  parentSessionId?: string | null;
  persona?: string;
}
export interface QuestionChoice {
  id: string;
  label: string;
}
export interface TodoItem {
  content: string;
  id: string;
  status?: "pending" | "in_progress" | "completed" | "cancelled";
}

export const ORBIT_RUNTIME_SCHEMA_SHA = "2c56c2ad9e7429454f590cd19a790987f5841db5";
export const ORBIT_EVENT_TYPES = ["session.status","assistant.message","assistant.delta","tool.call","tool.result","approval.asked","approval.resolved","question.asked","question.answered","todo.updated","usage","agent.started","agent.finished","agent.spawn_rejected","turn.failed"] as const;
export const TURN_ERROR_CODES = ["timeout","auth","rate_limited","provider_error","config"] as const;
export const TOOL_STATES = ["success","error","denied","interrupted"] as const;
