#!/usr/bin/env node
/**
 * Generates src/lib/events/orbit-event.gen.ts from the orbit-runtime A1 JSON Schema.
 * The source commit is pinned. Bump ORBIT_RUNTIME_SHA deliberately, then rerun `pnpm gen:events` and commit the output.
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const ORBIT_RUNTIME_REPO = "mindreon/orbit-runtime";
const ORBIT_RUNTIME_SHA = "2c56c2ad9e7429454f590cd19a790987f5841db5";
const SCHEMA_PATH = "schema/OrbitEvent.json";
const OUT = fileURLToPath(new URL("../src/lib/events/orbit-event.gen.ts", import.meta.url));

const url = `https://raw.githubusercontent.com/${ORBIT_RUNTIME_REPO}/${ORBIT_RUNTIME_SHA}/${SCHEMA_PATH}`;
const response = await fetch(url);
if (!response.ok) throw new Error(`GET ${url} -> ${response.status}`);
const schema = await response.json();

// Pydantic puts a title on every field, which makes json-schema-to-typescript emit one alias per field
// (Agentid, Agentid1, ...). Field titles carry no information, so drop them and keep model titles.
function dropFieldTitles(node) {
  if (!node || typeof node !== "object") return;
  for (const value of Object.values(node.properties ?? {})) {
    delete value.title;
    dropFieldTitles(value);
  }
  for (const value of Object.values(node.$defs ?? {})) dropFieldTitles(value);
}
const compiled = structuredClone(schema);
dropFieldTitles(compiled);

const types = await compile(compiled, "OrbitEvent", {
  additionalProperties: false,
  bannerComment: "",
  format: true,
  style: { semi: true, singleQuote: false, printWidth: 120 },
});

const eventTypes = schema?.properties?.type?.enum;
const turnErrorCodes = schema?.$defs?.TurnFailure?.properties?.errorCode?.enum;
const toolStates = schema?.properties?.toolState?.anyOf?.find((item) => Array.isArray(item.enum))?.enum;
if (!Array.isArray(eventTypes) || !Array.isArray(turnErrorCodes) || !Array.isArray(toolStates)) {
  throw new Error("OrbitEvent schema shape changed: type / TurnFailure.errorCode / toolState enums not found");
}

const header = `/* eslint-disable */
// Generated by scripts/gen-events.mjs. Do not edit by hand.
// Source: https://github.com/${ORBIT_RUNTIME_REPO}/blob/${ORBIT_RUNTIME_SHA}/${SCHEMA_PATH}
`;

const constants = `
export const ORBIT_RUNTIME_SCHEMA_SHA = ${JSON.stringify(ORBIT_RUNTIME_SHA)};
export const ORBIT_EVENT_TYPES = ${JSON.stringify(eventTypes)} as const;
export const TURN_ERROR_CODES = ${JSON.stringify(turnErrorCodes)} as const;
export const TOOL_STATES = ${JSON.stringify(toolStates)} as const;
`;

await writeFile(OUT, `${header}\n${types.trim()}\n${constants}`);
console.log(`wrote ${OUT} from ${ORBIT_RUNTIME_REPO}@${ORBIT_RUNTIME_SHA.slice(0, 8)}`);
